### ISSUE TITLE
[Bug]: I got OneSignal Working with Chrome and Edge perfectly, I can see the updated status in the Dashboard, Brave on the other hand is broken.

### ISSUE THREAD

**Issue by Inzendis** [OneSignal/OneSignal-Website-SDK#1155]
### What happened?

Pretty much Chrome works as intented and Brave doesnt. My shield in Brave is turned off and my other ad-blockers as well.

I keep getting Uncaught DOMException, The service worker is failing to install. 
Honestly Brave doesnt matter much, but I need it to work in safari. This will be used to send Push Notifications to PWA users in IOS and Android.

POV Chrome:

![image](https://github.com/OneSignal/OneSignal-Website-SDK/assets/80369840/3258a004-29b5-4095-8558-fa1f6b4ca445)

POV Edge:

![image](https://github.com/OneSignal/OneSignal-Website-SDK/assets/80369840/2c844c7b-d8ad-478e-a104-4633d36a1a6f)

POV Brave:
In the second picture there are workers that I cant unregister, they are straight up stuck. I cleared Brave browser and they are still there.
The log output below is the console from Brave.

![image](https://github.com/OneSignal/OneSignal-Website-SDK/assets/80369840/d971cb15-164d-4da5-a9d8-3c4e7b012603)
![image](https://github.com/OneSignal/OneSignal-Website-SDK/assets/80369840/eba6448a-c576-43a3-9d15-716dbf9aaeda)

### What browsers are you seeing the problem on?

Brave

### What operating system are you running?

Windows 10

### Steps to reproduce?

```Markdown
1. Followed the Web Quick Start docs until it mentions to jump to React if your are using React.
2. Im not using React alone, its NextJs 13.5+ App, but its pretty much the same thing with "use client"
3. The importScript sdk is in public and its the only Push Notification ServiceWorker.
4. Again, both Brave Shield and and Ad Blockers are disabled.
5. I cleared cookies, and all workers associated with OneSignal and localhost.
```

### What did you expect to happen?

To work the same as Chrome.

### Relevant log output

```Shell
Uncaught (in promise) SdkInitError: OneSignal: The OneSignal web SDK can only be initialized once. Extra initializations are ignored. Please remove calls initializing the SDK more than once.
    at bi.errorIfInitAlreadyCalled (InitHelper.js:316:19)
    at nn.<anonymous> (OneSignal.js:99:20)
    at Generator.next (<anonymous>)
    at r (tslib.es6.js:118:58)
errorIfInitAlreadyCalled @ InitHelper.js:316
(anonymous) @ OneSignal.js:99
r @ tslib.es6.js:118
Promise.then (async)
eval @ index.es.js:80
processItem @ ProcessOneSignalPushCalls.js:5
push @ OneSignal.js:194
push @ OneSignalDeferred.js:7
eval @ index.es.js:79
init @ index.es.js:77
runOneSignal @ ReactOneSignal.tsx:6
eval @ ReactOneSignal.tsx:25
commitHookEffectListMount @ react-dom.development.js:20004
invokePassiveEffectMountInDEV @ react-dom.development.js:22883
invokeEffectsInDev @ react-dom.development.js:25636
legacyCommitDoubleInvokeEffectsInDEV @ react-dom.development.js:25619
commitDoubleInvokeEffectsInDEV @ react-dom.development.js:25600
flushPassiveEffectsImpl @ react-dom.development.js:25309
flushPassiveEffects @ react-dom.development.js:25233
eval @ react-dom.development.js:24970
workLoop @ scheduler.development.js:261
flushWork @ scheduler.development.js:230
performWorkUntilDeadline @ scheduler.development.js:534
Show 15 more frames
Show less
OneSignalSDKWorker.js?appId=3&sdkVersion=160101:1 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.sw.js' failed to load.
    at http://localhost:3000/OneSignalSDKWorker.js?appId=7ebde2ce-822b-4ced-b19f-63e33084a4f3&sdkVersion=160101:1:1
(anonymous) @ OneSignalSDKWorker.js?appId=3&sdkVersion=160101:1
An unknown error occurred when fetching the script.
ServiceWorkerManager.js:279 [Service Worker Installation] Installing service worker failed TypeError: Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/OneSignalSDKWorker.js?appId=3&sdkVersion=160101'): ServiceWorker script evaluation failed
window.console.error @ app-index.js:32
console.error @ hydration-error-info.js:41
(anonymous) @ ServiceWorkerManager.js:279
a @ tslib.es6.js:119
Promise.then (async)
l @ tslib.es6.js:120
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
installWorker @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ SubscriptionManager.js:349
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
subscribeFcmFromPage @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ SubscriptionManager.js:105
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
subscribe @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ SubscriptionHelper.js:17
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
internalRegisterForPush @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ SubscriptionHelper.js:9
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
registerForPush @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ InitHelper.js:74
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
registerForPushNotifications @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ PromptsManager.js:114
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
internalShowNativePrompt @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ NotificationsNamespace.js:114
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
requestPermission @ OneSignalSDK.page.es6.js?v=160101:1
eval @ index.es.js:305
processItem @ ProcessOneSignalPushCalls.js:5
push @ OneSignal.js:194
push @ OneSignalDeferred.js:7
eval @ index.es.js:304
notificationsRequestPermission @ index.es.js:298
runOneSignal @ ReactOneSignal.tsx:10
await in runOneSignal (async)
eval @ ReactOneSignal.tsx:25
commitHookEffectListMount @ react-dom.development.js:20004
commitHookPassiveMountEffects @ react-dom.development.js:22057
reconnectPassiveEffects @ react-dom.development.js:22309
recursivelyTraverseReconnectPassiveEffects @ react-dom.development.js:22289
reconnectPassiveEffects @ react-dom.development.js:22307
recursivelyTraverseReconnectPassiveEffects @ react-dom.development.js:22289
commitPassiveMountOnFiber @ react-dom.development.js:22244
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22170
commitPassiveMountEffects @ react-dom.development.js:22128
flushPassiveEffectsImpl @ react-dom.development.js:25292
flushPassiveEffects @ react-dom.development.js:25233
eval @ react-dom.development.js:24970
workLoop @ scheduler.development.js:261
flushWork @ scheduler.development.js:230
performWorkUntilDeadline @ scheduler.development.js:534
Show 103 more frames
Show less
A bad HTTP response code (404) was received when fetching the script.
ServiceWorkerManager.js:312 
        
        
       GET http://localhost:3000/OneSignalSDK.sw.js?appId=3&sdkVersion=160101 404 (Not Found)
(anonymous) @ ServiceWorkerManager.js:312
a @ tslib.es6.js:119
Promise.then (async)
l @ tslib.es6.js:120
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
fallbackToUserModelBetaWorker @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ ServiceWorkerManager.js:280
a @ tslib.es6.js:119
Promise.then (async)
l @ tslib.es6.js:120
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
installWorker @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ SubscriptionManager.js:349
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
subscribeFcmFromPage @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ SubscriptionManager.js:105
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
subscribe @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ SubscriptionHelper.js:17
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
internalRegisterForPush @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ SubscriptionHelper.js:9
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
registerForPush @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ InitHelper.js:74
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
registerForPushNotifications @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ PromptsManager.js:114
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
internalShowNativePrompt @ OneSignalSDK.page.es6.js?v=160101:1
(anonymous) @ NotificationsNamespace.js:114
r @ tslib.es6.js:118
Promise.then (async)
l @ tslib.es6.js:120
(anonymous) @ tslib.es6.js:121
o @ tslib.es6.js:117
requestPermission @ OneSignalSDK.page.es6.js?v=160101:1
eval @ index.es.js:305
processItem @ ProcessOneSignalPushCalls.js:5
push @ OneSignal.js:194
push @ OneSignalDeferred.js:7
eval @ index.es.js:304
notificationsRequestPermission @ index.es.js:298
runOneSignal @ ReactOneSignal.tsx:10
await in runOneSignal (async)
eval @ ReactOneSignal.tsx:25
commitHookEffectListMount @ react-dom.development.js:20004
commitHookPassiveMountEffects @ react-dom.development.js:22057
reconnectPassiveEffects @ react-dom.development.js:22309
recursivelyTraverseReconnectPassiveEffects @ react-dom.development.js:22289
reconnectPassiveEffects @ react-dom.development.js:22307
recursivelyTraverseReconnectPassiveEffects @ react-dom.development.js:22289
commitPassiveMountOnFiber @ react-dom.development.js:22244
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22159
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22273
recursivelyTraversePassiveMountEffects @ react-dom.development.js:22140
commitPassiveMountOnFiber @ react-dom.development.js:22170
commitPassiveMountEffects @ react-dom.development.js:22128
flushPassiveEffectsImpl @ react-dom.development.js:25292
flushPassiveEffects @ react-dom.development.js:25233
eval @ react-dom.development.js:24970
workLoop @ scheduler.development.js:261
flushWork @ scheduler.development.js:230
performWorkUntilDeadline @ scheduler.development.js:534
Show 105 more frames
Show less
SubscriptionHelper.js:25 be: Registration of a Service Worker failed.
    at Ot.<anonymous> (https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.es6.js?v=160101:1:74072)
    at Generator.next (<anonymous>)
    at r (https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.es6.js?v=160101:1:260398)
```

**Comment by jkasten2** [comment]
@Inzendis Thanks for reporting this issue, see the selections bellow for my responses to your questions:

## Brave
It seems there is a Brave bug where `importScripts` URLs are still blocked for Service Workers when shields are off for the site.
A workaround I found for Brave is to go to brave://settings/shields then select "Disabled" for "Trackers & ads blocking".
* This is a global setting so it isn't ideal but does allow testing

I opened an issue with Brave, feel free to follow it as well:
https://github.com/brave/brave-browser/issues/35461

## Safari
> Honestly Brave doesnt matter much, but I need it to work in safari. This will be used to send Push Notifications to PWA users in IOS and Android.

Are you seeing any issues with Safari on iOS or Safari?
* Note that with iOS there are some extra requirements; being a web app and adding to home screen. See the OneSignal documentation page [Mobile Web Push for iOS/iPadOS](https://documentation.onesignal.com/docs/safari-web-push-for-ios) for more details.

**Comment by jkasten2** [comment]
Closing due to no response
