### ISSUE TITLE
[Bug]: Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by albertoderodrigo** [OneSignal/OneSignal-Website-SDK#1203]
### What happened?

When we open the console on our app we frequently see the error (see relevant logs) when your sdk calls to `logMethodCall` on the operations `OperationCache.enqueue`.

This is an screenshot of the content of the arguments:

<img width="656" alt="Screenshot 2024-10-14 at 07 54 51" src="https://github.com/user-attachments/assets/cc9cbdc1-3955-455b-9f38-3880daebaa58">

The OneSignal version is `160203`

### What browsers are you seeing the problem on?

Chrome (Chromium)

### What operating system are you running?

macos Sequoia 15.0.1

### Steps to reproduce?

```Markdown
Open the console
```

### What did you expect to happen?

Nothing

### Relevant log output

```Shell
Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'j'
    |     property '_zoneDelegate' -> object with constructor '_'
    --- property '_zone' closes the circle
    at JSON.stringify (<anonymous>)
    at eval (eval at logMethodCall (OneSignalSDK.page.es6.js?v=160203:1:261990), <anonymous>:1:6)
    at d.logMethodCall (OneSignalSDK.page.es6.js?v=160203:1:261990)
    at g (OneSignalSDK.page.es6.js?v=160203:1:264019)
    at $i.enqueue (OneSignalSDK.page.es6.js?v=160203:1:205036)
    at Qi.<anonymous> (OneSignalSDK.page.es6.js?v=160203:1:207530)
    at Generator.next (<anonymous>)
    at r (OneSignalSDK.page.es6.js?v=160203:1:267690)
    at _.invoke (polyfills.js:20:19120)
    at j.run (polyfills.js:20:14358)
    at polyfills.js:20:25537
    at _.invokeTask (polyfills.js:20:19738)
    at j.runTask (polyfills.js:20:15013)
    at ae (polyfills.js:20:21770)
    at y.invokeTask [as invoke] (polyfills.js:20:20823)
    at B (polyfills.js:20:4736)
    at W (polyfills.js:20:5034)
    at IDBRequest.J (polyfills.js:20:5301)
```

**Comment by fadi-george** [comment]
@albertoderodrigo Hello, are you still getting this error. If so, can you provide code snippets on how you're using the sdks e.g. `OneSignal.User.addAlias`
