### ISSUE TITLE
Unable to build from this repository

### ISSUE THREAD

**Issue by jammer99** [OneSignal/OneSignal-Website-SDK#237]
I have cloned this repository on my local machine and even after successfully running `npm install` i am unable to run `gulp` as mentioned in the readme.

I am a noob in this area, this is the error that i get
`[11:51:57] No gulpfile found`

Please help me.

P.s. if this helps,
OS Windows 10
node 6.10.3
npm 5.0.3
gulp CLI 3.9.1
node-gyp 3.6.2

**Comment by jasonpang** [comment]
@jammer99 Sorry for the lack of clearer instructions, can you try:

```
# Do this in the root project directory
chmod +x sdk
# Install yarn first if you don't have it 
yarn
./sdk build --tests
./sdk test
```

**Comment by jammer99** [comment]
Unfortunately, i am on windows :(
I was able to run yarn, but not the bash scripts. any other alternative?

**Comment by jasonpang** [comment]
@jammer99, sorry about the lack of cross-platform build support. You definitely don't need to build the SDK from our source code in order to use push notifications. Have you seen [our web push setup guide](https://documentation.onesignal.com/docs/web-push-setup)? We recommend linking to https://cdn.onesignal.com/sdks/OneSignalSDK.js in order to always get the most up-to-date SDK.

What specific build error did you encounter on Windows?

**Comment by jammer99** [comment]
I tried it on ubuntu system, I am getting the same error on running gulp.
`[12:51:22] No gulpfile found`

Also I tried with yarn
this is the error i am getting.
```
root@Jammer:/mnt/d/Github/OneSignal-Website-SDK# chmod +x sdk

root@Jammer:/mnt/d/Github/OneSignal-Website-SDK# yarn
ERROR: There are no scenarios; must have at least one.

root@Jammer:/mnt/d/Github/OneSignal-Website-SDK# ./sdk build --tests
/mnt/d/Github/OneSignal-Website-SDK/sdk:136
  static async printFinalBuildTimeString(context, sdkVersion) {
               ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
root@Jammer:/mnt/d/Github/OneSignal-Website-SDK# ./sdk build --tests
```

Also, I just want to see the build process, i am not planning to use it on my project. I am using the CDN link only.

**Comment by jasonpang** [comment]
Hey @jammer99,

- You'll have to install the latest node (I forgot which is the minimum version, but it must support `async` and `await` without needing to use the `--harmony` flag which enables experimental features. `async` and `await` landed without needing to use a flag in a recent version of node v7.x+ but I forget which, so install the latest using `nvm` or something similar). We use the latest JS features in our build script so only the latest version of Node can support this.

- It looks like your `yarn` package [is a different software package of the same name](https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365). Use [this guide to install Yarn on Linux](https://yarnpkg.com/en/docs/install#linux-tab).

**Comment by jwilm** [comment]
Closing due to inactivity
