### ISSUE TITLE
PermissionMessageDismissedError using Slidedown Permission Message

### ISSUE THREAD

**Issue by ayumihamsaki** [OneSignal/OneSignal-Website-SDK#252]
Hi,

I think everything is working fine except I see this error message in Google Canary Dev Tools:

```
Stack Version:

Uncaught (in promise) PermissionMessageDismissedError {message: "The permission message was previously dismissed.", name: "PermissionMessageDismissedError", stack: "PermissionMessageDismissedError: The permission me…m/sdks/OneSignalSDK.js:1:1486)↵    at <anonymous>"}message: "The permission message was previously dismissed."name: "PermissionMessageDismissedError"stack: "PermissionMessageDismissedError: The permission message was previously dismissed.↵    at Function.<anonymous> (https://cdn.onesignal.com/sdks/OneSignalSDK.js:1:139603)↵    at i (https://cdn.onesignal.com/sdks/OneSignalSDK.js:1:2384)↵    at Object.next (https://cdn.onesignal.com/sdks/OneSignalSDK.js:1:1719)↵    at s (https://cdn.onesignal.com/sdks/OneSignalSDK.js:1:1486)↵    at <anonymous>"__proto__: tconstructor: ƒ PermissionMessageDismissedError()arguments: (...)caller: (...)length: 0name: "PermissionMessageDismissedError"prototype: tconstructor: ƒ PermissionMessageDismissedError()arguments: (...)caller: (...)length: 0name: "PermissionMessageDismissedError"prototype: t {constructor: ƒ}__proto__: ƒ t(t)[[FunctionLocation]]: PermissionMessageDismissedError.ts:5[[Scopes]]: Scopes[3]__proto__: t__proto__: ƒ t(t)[[FunctionLocation]]: PermissionMessageDismissedError.ts:5[[Scopes]]: Scopes[3]__proto__: t
s @ tslib.es6.js:62
Promise resolved (async)
u @ tslib.es6.js:64
s @ tslib.es6.js:62
Promise resolved (async)
u @ tslib.es6.js:64
s @ tslib.es6.js:62
Promise resolved (async)
u @ tslib.es6.js:64
s @ tslib.es6.js:62
Promise resolved (async)
u @ tslib.es6.js:64
s @ tslib.es6.js:62
Promise resolved (async)
u @ tslib.es6.js:64
s @ tslib.es6.js:62
Promise resolved (async)
u @ tslib.es6.js:64
(anonymous) @ tslib.es6.js:65
u @ tslib.es6.js:61
e.showHttpPrompt @ OneSignal.ts:261
(anonymous) @ all-scripts.js:1
e.push @ OneSignal.ts:782
(anonymous) @ entry.ts:31
t @ bootstrap bf988049d4e6edbf9423:19
(anonymous) @ bootstrap bf988049d4e6edbf9423:65
(anonymous) @ bootstrap bf988049d4e6edbf9423:65

Short Version:

PermissionMessageDismissedError {message: "The permission message was previously dismissed.", name: "PermissionMessageDismissedError", stack: "PermissionMessageDismissedError: The permission me…m/sdks/OneSignalSDK.js:1:1486)↵    at <anonymous>"}

https://cdn.onesignal.com/node_modules/tslib/tslib.es6.js:62 Uncaught (in promise) 
```

Below is my Javascript API Call:

```
var OneSignal = window.OneSignal || [];

OneSignal.push(["init", {
  appId: "xxx",
  safari_web_id: "xxx",
  autoRegister: false,
  notifyButton: {
    enable: false /* Set to false to hide */
  },
  promptOptions: {
        /* These prompt options values configure both the HTTP prompt and the HTTP popup. */
	    siteName: "xxx",
        /* actionMessage limited to 90 characters */
        actionMessage: "xxx",
        /* acceptButtonText limited to 15 characters */
        acceptButtonText: "ACCEPT",
        /* cancelButtonText limited to 15 characters */
        cancelButtonText: "NO THANKS"
  },
  welcomeNotification: {
    "title": "xxx",
    "message": "xxx",
    "url": "https://www.example.com"
  }  
}]);

/* Turn on the Slidedown Permission Message */

OneSignal.push(function() {
  OneSignal.showHttpPrompt();
});
```

I just want to know if my API Code is wrong or there is a Promise Error in your SDK Code?

cc @jasonpang

**Comment by jasonpang** [comment]
Hey @ayumihamsaki,

Our SDK has a promise error in this case; we're fixing this now!

**Comment by ayumihamsaki** [comment]
@jasonpang Thanks for letting me know, I will leave this issue open and leave it up to you when you want to close it,...

**Comment by scocio** [comment]
@jasonpang still seeing this issue

**Comment by loichnh** [comment]
Having the same issue

**Comment by y-a-v-a** [comment]
@jasonpang what's the status of this issue?

**Comment by jasonpang** [comment]
Hey everyone, we're aware of this issue and we hope to fix it soon. There are two separate issues causing this error. The end behavior of not showing the prompt when visitors have already dismissed it is roughly correct, but a lot of the instances of the error you're seeing are being displayed when they shouldn't and we'll be refactoring how the prompts are handled to make sure the errors are only shown when appropriate.

**Comment by y-a-v-a** [comment]
Any progress already?

**Comment by jasonpang** [comment]
PermissionMessageDismissedError should no longer be throwing and only showing as a silent log message.

**Comment by y-a-v-a** [comment]
Thanks! As far as we currently see, the error doesn't occur any longer!

**Comment by ayumihamsaki** [comment]
@jasonpang Thanks for the fix I can't see any issues now, so going to close this.

**Comment by iamalisajid** [comment]
Any update on this? Still facing this issue.

**Comment by iamalisajid** [comment]
[Here's](https://imgur.com/a/Ejqa1zo) a small stack-trace.

**Comment by alocke12992** [comment]
Experiencing this now as well.
